---
- name: Thu thập subscription info và upload lên S3-compatible
  hosts: linux
  gather_facts: no

  vars:
    s3_endpoint: "https://s3hn.smartcloud.vn"
    s3_bucket: "webhosting"
    s3_prefix: "plesk/subscription_info"
    aws_region: "us-east-1"

    # lưu file trên AWX runner / localhost
    local_dir: "/tmp/subscription_info"
    local_file: "{{ local_dir }}/{{ inventory_hostname }}_subs_linux.csv"

    # tạo timestamp 1 lần để ổn định (không bị lệch giữa task)
    ts: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    s3_key: "{{ s3_prefix }}/{{ inventory_hostname }}_subs_linux_{{ ts }}.csv"

    # bạn truyền 2 biến này từ AWX Credential / extra_vars
    # access_key: "xxxx"
    # secret_key: "yyyy"

  tasks:
    - name: Lấy danh sách domain
      shell: plesk bin subscription --list
      register: domain_list_linux

    - name: Lấy thông tin domain
      shell: plesk bin subscription --info {{ item }}
      loop: "{{ domain_list_linux.stdout_lines }}"
      register: subs_info

    - name: Tạo thư mục file trên runner
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ local_dir }}"
        state: directory
        mode: "0755"

    - name: Ghi CSV trên runner
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "{{ local_file }}"
        mode: "0644"
        content: |
          Domain,Creation Date,Expiration Date
          {% for r in subs_info.results %}
          {% set domain = r.item %}
          {% set created_line = (r.stdout_lines | select('search','Creation date:') | list | first | default('Creation date:')) %}
          {% set expired_line = (r.stdout_lines | select('search','Expiration date:') | list | first | default('Expiration date:')) %}
          {{ domain }},{{ created_line.split(':',1)[1] | default('') | trim }},{{ expired_line.split(':',1)[1] | default('') | trim }}
          {% endfor %}

    - name: Download rclone (portable) on localhost
      delegate_to: localhost
      ansible.builtin.shell: |
        set -e
        mkdir -p /tmp/rclone-bin
        if [ ! -x /tmp/rclone-bin/rclone ]; then
          cd /tmp/rclone-bin
          curl -fsSL -o rclone.zip https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip -o rclone.zip >/dev/null
          mv rclone-*-linux-amd64/rclone .
          chmod +x rclone
        fi
      args:
        executable: /bin/bash

    - name: Upload lên S3-compatible bằng rclone (dùng AWS Credential của AWX)
    delegate_to: localhost
    ansible.builtin.command: >
      /tmp/rclone-bin/rclone copyto {{ local_file }}
      :s3:{{ s3_bucket }}/{{ s3_key }}
      --s3-provider Other
      --s3-endpoint {{ s3_endpoint }}
      --s3-region {{ aws_region }}
      --s3-access-key-id {{ lookup('env','AWS_ACCESS_KEY_ID') }}
      --s3-secret-access-key {{ lookup('env','AWS_SECRET_ACCESS_KEY') }}
    register: put_result
    changed_when: put_result.rc == 0
