---
- name: Add cron job for rsync backup with log
  hosts: all
  tasks:
    - name: Add a cron job to run rsync backup every Sunday at 0:00 and save logs
      cron:
        name: "Weekly rsync backup with log"
        minute: "0"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "0"
        job: "/root/scripts/rsync_backup_new.sh >> /var/log/rsync_backup_new.log 2>&1"
