- name: Change root password
  hosts: all
  become: yes  # This ensures that the task runs with elevated privileges
#  vars_files:
#    - password.yaml
  tasks:
#    - name: Debug passwords variable
#      debug:
#        var: passwords

#    - name: Debug specific password
#      debug:
#        msg: "Password for {{ inventory_hostname }} is {{ passwords[inventory_hostname] }}"

#    - name: Change root password for user
#        user:
#          name: "root"
#          password: "{{ passwords[inventory_hostname] | password_hash('sha512') }}"
#
    - name: Run Python script on Ansible controller to update server information via API
      local_action:
        module: command
        cmd: "python3 inbound_api_for_password_history_update.py"
      environment:
        VM_NAME: "{{ inventory_hostname }}"  # Truyền tên máy chủ
      register: api_update_output

    - name: Debug Python script output
      debug:
        var: api_update_output.stdout
